### ISSUE TITLE
it never computes for 8X8 string

### ISSUE THREAD

**Issue by SyedOsman33** [MilanPecov/15-Puzzle-Solvers#1]
puzzle = str([[1, 2, 6],[4, 0, 5], [8, 3, 7]])
    end = str([[1, 2, 3],[4, 5, 6], [7, 8, 0]])

"i've tried by changing this and little more modifications like,
 distance += abs(i - (m[i][j]/3)) + abs(j -  (m[i][j]%3));

and also in moves function ! 
Can you help ?

**Comment by MilanPecov** [comment]
I pushed a fix to support various puzzle size
