### ISSUE TITLE
It loops forever with this combination

### ISSUE THREAD

**Issue by dliloch** [MilanPecov/15-Puzzle-Solvers#2]
Hello,
This combination makes it loop forever. 
 puzzle = Puzzle([[1, 2, 3, 7], [12, 8, 15, 4], [13, 10, 11, 5], [ 9, 6, 14, 0]])
There are other combinations as well.
Thanks,

**Comment by MilanPecov** [comment]
I added a check if the puzzle is solvable or not, this should be fixed now
